---
kind: pipeline
type: docker
name: w3c validate html2php2html
steps:
  - name: initialize git submodules
    image: alpine/git
    commands:
      - git submodule update --init
  - name: generate html from php
    image: php:7.4-cli
    commands:
      - ./convert.sh | php | tee index.html
  - name: w3c validate
    image: python:3.9-bullseye
    commands:
      - pip install -U Online-W3C-Validator
      - w3c_validator index.html
---
kind: pipeline
type: docker
name: w3c validate php2html
steps:
  - name: generate html from php
    image: php:7.4-cli
    commands:
      - php ./output/index.php | tee index.html
  - name: w3c validate
    image: python:3.9-bullseye
    commands:
      - pip install -U Online-W3C-Validator
      - w3c_validator index.html
