# vi:syntax=dockerfile
FROM php:7.4-apache

WORKDIR /usr/src
COPY ./CNMT-310-HTML-Assignment ./CNMT-310-HTML-Assignment
COPY ./convert.sh .
COPY ./init.sh .

RUN ./init.sh
RUN cp ./output/* /var/www/html
WORKDIR /var/www/html
